SET (CURL_INCLUDE_DIR   "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../curl-7.19/parts/part/include" CACHE PATH "curl inc)." FORCE)
SET (CURL_LIBRARY       "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../curl-7.19/parts/part/lib" CACHE PATH "curl lib)." FORCE)
SET (CURL_LIBRARIES     "-lcurl -Wl,-rpath -Wl,/home/kiorky/minitage/mt/dependencies/cmake-2.6/../curl-7.19/parts/part/lib -L/home/kiorky/minitage/mt/dependencies/cmake-2.6/../curl-7.19/parts/part/lib" CACHE PATH "curl libs)." FORCE)
SET (ZLIB_INCLUDE_DIR   "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../zlib-1.2/parts/part/include" CACHE PATH "zlib inc)." FORCE)
SET (ZLIB_LIBRARY       "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../zlib-1.2/parts/part/lib" CACHE PATH "zlib lib)." FORCE)
SET (ZLIB_LIBRARIES     "-lz -Wl,-rpath -Wl,/home/kiorky/minitage/mt/dependencies/cmake-2.6/../zlib-1.2/parts/part/lib -L/home/kiorky/minitage/mt/dependencies/cmake-2.6/../zlib-7.19/parts/part/lib" CACHE PATH "zlib libs)." FORCE)
SET (EXPAT_INCLUDE_DIR  "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../expat-2.0/parts/part/include" CACHE PATH "expat inc)." FORCE)
SET (EXPAT_LIBRARY      "/home/kiorky/minitage/mt/dependencies/cmake-2.6/../expat-2.0/parts/part/lib" CACHE PATH "expat lib)." FORCE)
SET (EXPAT_LIBRARIE     "-lexpat -Wl,-rpath -Wl,/home/kiorky/minitage/mt/dependencies/cmake-2.6/../expat-2.0/parts/part/lib -L/home/kiorky/minitage/mt/dependencies/cmake-2.6/../expat-2.0/parts/part/lib" CACHE PATH "expat libs)." FORCE)
