# Generated by /home/kiorky/minitage/mt/dependencies/cmake-2.6/__minitage__part__tmp/cmake-2.6.3/bootstrap
# Default cmake settings.  These may be overridden any settings below.
SET (CMAKE_INSTALL_PREFIX "/home/kiorky/minitage/mt/dependencies/cmake-2.6/parts/part" CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
SET (CMAKE_DOC_DIR "/doc/cmake-2.6" CACHE PATH "Install location for documentation (relative to prefix)." FORCE)
SET (CMAKE_MAN_DIR "/man" CACHE PATH "Install location for man pages (relative to prefix)." FORCE)
SET (CMAKE_DATA_DIR "/share/cmake-2.6" CACHE PATH "curl lin" FORCE)
SET (CURL_INCLUDE_DIR "/home/kiorky/minitage/mt/dependencies/curl-7.19/parts/part/include" CACHE PATH "curl inc)." FORCE)
